name: codecov

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache pnpm-lock.yaml
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: hack for singe file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp pnpm-lock.yaml package-temp-dir

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/pnpm-lock.yaml') }}
          
      - name: install pnpm
        run: npm -g install pnpm
        
      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: pnpm i


  node:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        # with:
        #   token: ${{ secrets.ACCESS_TOKEN }}
      # - name: Checkout submodules
      #   uses: actions/checkout@v2
      #   with:
      #     repository: tangjinzhou/antdv-demo
      #     token: ${{ secrets.ACCESS_TOKEN }}
      #     path: antdv-demo
      #     submodules: true

      - name: restore cache from pnpm-lock.yaml
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/pnpm-lock.yaml') }}

      - name: Generate coverage report
        run: npm test
        env:
          COVERAGE: "true"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

    needs: setup
